// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.last_seen_buildid", "20200602222727");
user_pref("app.normandy.migrationsApplied", 9);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.discoverystream.isCollectionDismissible", true);
user_pref("app.normandy.startupRolloutPrefs.editor.truncate_user_pastes", true);
user_pref("app.normandy.user_id", "c2219cfa-3b50-4073-96f0-c5c04edd9096");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1598593197);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1598575295);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1598575293);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1598593317);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1598593227);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 6325);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.download.panel.shown", true);
user_pref("browser.migration.version", 94);
user_pref("browser.newtabpage.activity-stream.impressionId", "{2082ea8d-4310-4a3c-8914-7472a93fb437}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1598593231671");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1598595014671");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1598575293087");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1598578893087");
user_pref("browser.search.cohort", "nov17-2");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1598575292");
user_pref("browser.startup.homepage_override.buildID", "20200602222727");
user_pref("browser.startup.homepage_override.mstone", "77.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1598575292);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Yahoo!");
user_pref("distribution.iniFile.exists.appversion", "77.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("distribution.mint.bookmarksProcessed", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.push.userAgentID", "5cf57b723a854226af0e3bbb4834aca7");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 32);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppVersion", "77.0.1");
user_pref("extensions.lastPlatformVersion", "77.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.doh-rollout@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"b6afd106-857a-48a5-8a49-cae775058b53\",\"formautofill@mozilla.org\":\"18b4c6e2-e113-4bbf-8906-57a45a589657\",\"screenshots@mozilla.org\":\"487d8d83-6d3e-4371-8637-cffbfd9d131e\",\"webcompat-reporter@mozilla.org\":\"e87703a4-c7eb-490c-8a63-1f80ee426c67\",\"webcompat@mozilla.org\":\"a277d54a-975c-4d65-8dbf-118c6175349f\",\"default-theme@mozilla.org\":\"37191ffa-c225-4398-a925-d4997311acc5\",\"yahoo@search.mozilla.org\":\"6b7ff6a6-bdde-4629-8b35-31afb9c6050f\",\"startpage@search.mozilla.org\":\"d61d6c84-7087-457f-bc5f-edf92135e054\",\"duckduckgo@search.mozilla.org\":\"e7fb0a6d-25a0-4202-abec-3637df8fcfd7\",\"twitter@search.mozilla.org\":\"9b269775-50cc-4872-b6f4-7c23fbb94a93\",\"wikipedia@search.mozilla.org\":\"a5b03270-bfa3-4291-8073-449b92daf670\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1598593213);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20200602222727");
user_pref("media.gmp-manager.lastCheck", 1598593212);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.remote_settings.crlite_filters.checked", 1598593212);
user_pref("security.remote_settings.intermediates.checked", 1598593212);
user_pref("security.sandbox.content.tempDirSuffix", "77c09e2b-f62c-45af-9535-eaa866265b47");
user_pref("security.sandbox.plugin.tempDirSuffix", "5ec640a9-c0af-4421-9e2a-a58f47b3ee4b");
user_pref("services.blocklist.addons.checked", 1598593212);
user_pref("services.blocklist.gfx.checked", 1598593212);
user_pref("services.blocklist.pinning.checked", 1598593212);
user_pref("services.blocklist.plugins.checked", 1598593212);
user_pref("services.settings.clock_skew_seconds", 0);
user_pref("services.settings.last_etag", "\"1598572904754\"");
user_pref("services.settings.last_update_seconds", 1598593212);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1598593212);
user_pref("services.settings.main.cfr-fxa.last_check", 1598593212);
user_pref("services.settings.main.cfr.last_check", 1598593212);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1598593212);
user_pref("services.settings.main.hijack-blocklists.last_check", 1598593212);
user_pref("services.settings.main.language-dictionaries.last_check", 1598593212);
user_pref("services.settings.main.messaging-experiments.last_check", 1598593212);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1598593212);
user_pref("services.settings.main.public-suffix-list.last_check", 1598593212);
user_pref("services.settings.main.search-config.last_check", 1598593212);
user_pref("services.settings.main.sites-classification.last_check", 1598593212);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1598593212);
user_pref("services.settings.main.whats-new-panel.last_check", 1598593212);
user_pref("services.settings.security.onecrl.checked", 1598593212);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1598593165);
user_pref("toolkit.telemetry.cachedClientID", "a2a7a263-1401-4c2e-b6d5-da5d967e3729");
user_pref("toolkit.telemetry.previousBuildID", "20200602222727");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
